enableTelemetry: false

nodeLinker: node-modules

npmRegistries:
  //npm-proxy.docplanner.io:
    npmAlwaysAuth: true
    npmAuthToken: SXiMtCZL12GLoRSLYFMrtDCMWBrW7c+ZBr6IolBPBR497KFv/LTRCF/7EM04hYvGctNenPwLyqxhZxCTfRt/Gg==

npmRegistryServer: "https://npm-proxy.docplanner.io"

